### ISSUE TITLE
Crash occurs for large values of host count

### ISSUE THREAD

**Issue by lilchurro** [CyberReboot/gensynet#4]
Reported by @cglewis 
This function seemed to crash sometimes when divvying up hosts among a variable number of subnets.
```
>>> gensynet.randomize_subnet_breakdown(1000, 104, 150)
DEBUG: subnet count: 150    nodes left: 850
DEBUG: subnet count: 114    nodes left: 736
DEBUG: subnet count: 125    nodes left: 611
DEBUG: subnet count: 116    nodes left: 495
DEBUG: subnet count: 144    nodes left: 351
DEBUG: subnet count: 141    nodes left: 210
DEBUG: subnet count: 125    nodes left: 85
DEBUG: looping with s=1, count=114, left=85
DEBUG: looping with s=0, count=150, left=84
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/achang/Projects/gensynet/gensynet.py", line 324, in randomize_subnet_breakdown
    subnets.remove(s)
ValueError: list.remove(x): x not in list
```

**Comment by lilchurro** [comment]
Found the source of the problem; the logic to the function was:
- divvy up a randomized number of hosts to some subnet, until the number of remaining hosts to be divvied is less than the requested minimum.
- Divvy up the remainder among the existing subnets, all the while removing maxed out subnets from consideration. 

The latter point was not properly expressed by the code, causing whole subnets to be removed from the returned list, rather than removing the indices from consideration. This has since been fixed.

**Comment by lilchurro** [comment]
I think I'm going to close this issue now.
